server:
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/dojo-spring
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
